### ISSUE TITLE
ElfObjectFile read file > 2GB

### ISSUE THREAD

**Issue by onSec-fr** [xoofx/LibObjectFile#13]
Hello,
Thx for your work!

I ran into a problem trying to read a file bigger than 2GB because the System.IO.MemoryStream capacity parameter is expecting an integer. I'm not sure it has anything to do with your library, but if so, could you provide a workaround ? 

![Screenshot_4](https://user-images.githubusercontent.com/59887731/82905191-d73e8980-9f63-11ea-805e-67d7491e6195.png)

**Comment by onSec-fr** [comment]
Note : Usually I could read the file in chunks but how to do it because ElfObjectFile.Read is expecting a stream ?

**Comment by xoofx** [comment]
Sorry to get back to you on this only now, I completely forgot about this issue.

So by default, `ElfObjectFile` will load the section in memory if you are in read-write mode, otherwise you should be able to load the sections in read-only mode with `ElfReaderOptions.ReadOnly`.
