### ISSUE TITLE
Error when reading created elf

### ISSUE THREAD

**Issue by furesoft** [xoofx/LibObjectFile#17]
when I create an ELF File and call verify all is good.

When I want to read this created elf file the following error  occurs: "Unexpected error while reading ELF object file"
with the id: ELF_ERR_InvalidSectionHeaderStreamOffset

**Comment by xoofx** [comment]
I can't tell anything from this description. Also, I have no time available to follow this project these days, so you have to investigate this yourself by debugging the library if it doesn't work for your case.
