### ISSUE TITLE
ELF files load with 12 erros

### ISSUE THREAD

**Issue by bruno-garcia** [xoofx/LibObjectFile#9]
The files failing to load as requested on #5 

https://github.com/bruno-garcia/elf-parsing-repro/blob/master/Console/Files/libchrome.so

https://github.com/bruno-garcia/elf-parsing-repro/blob/master/Console/Files/libdl.so

**Comment by xoofx** [comment]
This should be fixed by commit 4db8888 (I only tested `libchrome.so`) and should be available shortly in `0.3.3`

**Comment by bruno-garcia** [comment]
I tried on both files of my repro and it works now!
Thanks a lot @xoofx 

At some point I'll swap again ELFSharp for LibObjectFile on SymbolCollector and see how it works. Now it requires Mach-O too so I think I'll need to figure out debug-id/code-id here first.
